name: Build iOS Static Library

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
    
    - name: Select Xcode
      run: |
        sudo xcode-select -switch /Applications/Xcode.app
        xcodebuild -version
      
    - name: Prepare build environment
      run: |
        pwd
        ls -la
        echo "Creating build directory..."
        mkdir -p build/lua
        cd build/lua
        echo "Current directory: $(pwd)"
        
        echo "Creating Xcode build directories..."
        mkdir -p build/lua.build/Release-iphoneos/lua.build
        mkdir -p build/lua.build/Release-iphonesimulator/lua.build
        chmod -R 755 build
        
        echo "Linking source files..."
        for file in ../../*.{h,c}; do
          if [ -f "$file" ] && [[ "$file" != *"/lua.c" && "$file" != *"/onelua.c" && "$file" != *"/ltests.c" ]]; then
            echo "Linking: $file"
            ln -sf "$file" .
          fi
        done
        
        echo "Build directory contents:"
        ls -la
        
    - name: Create Xcode project
      run: |
        cd build/lua
        echo "Current directory: $(pwd)"
        chmod +x ../../generate-xcodeproj.sh
        ../../generate-xcodeproj.sh
        
        echo "Xcode project contents:"
        ls -la lua.xcodeproj/
        
    - name: Build static library
      run: |
        cd build/lua
        echo "Current directory: $(pwd)"
        set -e
        
        # Create required build directories
        mkdir -p "$(pwd)/DerivedData/lua.build/Release-iphoneos/lua.build"
        chmod -R 755 "$(pwd)/DerivedData"
        
        echo "Building for iOS devices (arm64)..."
        xcodebuild clean build \
          -project lua.xcodeproj \
          -target lua \
          -configuration Release \
          -sdk iphoneos \
          ONLY_ACTIVE_ARCH=NO \
          BUILD_FOR_DISTRIBUTION=YES \
          ARCHS="arm64" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGN_IDENTITY="" \
          CONFIGURATION_BUILD_DIR="$(pwd)" \
          OBJROOT="$(pwd)/DerivedData" \
          SYMROOT="$(pwd)/DerivedData" \
          -verbose
        
        echo "Checking library file..."
        if [ ! -f "liblua.a" ]; then
          echo "Error: iOS device library not found"
          echo "Current directory: $(pwd)"
          echo "Directory contents:"
          ls -la
          exit 1
        fi
        
        echo "Build completed successfully!"
        ls -la liblua.a
        file liblua.a
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ios-static-library
        path: build/lua/liblua.a
        if-no-files-found: error 