name: iOS Static Library Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build iOS Static Library
    runs-on: macos-13
    
    steps:
    - uses: actions/checkout@v4
      
    - name: Select Xcode
      run: |
        sudo xcode-select -switch /Applications/Xcode.app
        xcodebuild -version
      
    - name: Prepare Build Environment
      run: |
        mkdir -p build/lua
        cd build/lua
        for file in ../../*.{c,h}; do
          if [ -f "$file" ]; then
            ln -sf "$file" .
          fi
        done
        
    - name: Create Xcode Project
      working-directory: build/lua
      run: |
        chmod +x ../../.github/workflows/generate-xcodeproj.sh
        ../../.github/workflows/generate-xcodeproj.sh
        
    - name: Build Static Library
      working-directory: build/lua
      run: |
        set -e
        
        echo "Building for iOS devices (arm64)..."
        xcodebuild clean build \
          -project lua.xcodeproj \
          -configuration Release \
          -sdk iphoneos \
          ONLY_ACTIVE_ARCH=NO \
          BUILD_DIR="../" \
          BUILD_FOR_DISTRIBUTION=YES \
          ARCHS="arm64" \
          SKIP_INSTALL=NO \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGN_IDENTITY="" || exit 1
          
        echo "Building for iOS Simulator (x86_64, arm64)..."
        xcodebuild clean build \
          -project lua.xcodeproj \
          -configuration Release \
          -sdk iphonesimulator \
          ONLY_ACTIVE_ARCH=NO \
          BUILD_DIR="../" \
          BUILD_FOR_DISTRIBUTION=YES \
          ARCHS="x86_64 arm64" \
          SKIP_INSTALL=NO \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGN_IDENTITY="" || exit 1
          
        echo "Creating universal binary..."
        if [ ! -f "../Release-iphoneos/liblua.a" ]; then
          echo "Error: iOS device library not found"
          exit 1
        fi
        
        if [ ! -f "../Release-iphonesimulator/liblua.a" ]; then
          echo "Error: iOS simulator library not found"
          exit 1
        fi
        
        lipo -create \
          ../Release-iphoneos/liblua.a \
          ../Release-iphonesimulator/liblua.a \
          -output ../liblua.a
          
        if [ ! -f "../liblua.a" ]; then
          echo "Error: Failed to create universal binary"
          exit 1
        fi
        
        echo "Build completed successfully"
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ios-static-library
        path: build/liblua.a
        if-no-files-found: error 