name: Build iOS Static Library

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-13

    steps:
    - uses: actions/checkout@v2
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode.app
      
    - name: Check Xcode version
      run: xcodebuild -version
      
    - name: Prepare build environment
      run: |
        cd lua
        mkdir -p build
        cd build
        ln -s ../../lua/*.h .
        ln -s ../../lua/*.c .
        
    - name: Create Xcode project
      run: |
        cd lua/build
        chmod +x ../../.github/workflows/generate-xcodeproj.sh
        ../../.github/workflows/generate-xcodeproj.sh
        
    - name: Build static library
      run: |
        cd lua/build
        set -e
        echo "Building for iOS devices (arm64)..."
        xcodebuild -project lua.xcodeproj -target lua -configuration Release -sdk iphoneos -verbose
        
        echo "Building for iOS Simulator (x86_64, arm64)..."
        xcodebuild -project lua.xcodeproj -target lua -configuration Release -sdk iphonesimulator -verbose
        
        echo "Checking build outputs..."
        ls -la build/Release-iphoneos/
        ls -la build/Release-iphonesimulator/
        
        if [ ! -f "build/Release-iphoneos/liblua.a" ]; then
          echo "Error: iOS device library not found"
          exit 1
        fi
        
        if [ ! -f "build/Release-iphonesimulator/liblua.a" ]; then
          echo "Error: iOS simulator library not found"
          exit 1
        fi
        
        echo "Creating universal binary..."
        lipo -create \
          build/Release-iphoneos/liblua.a \
          build/Release-iphonesimulator/liblua.a \
          -output liblua.a
        
        echo "Build completed successfully!"
        
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: liblua
        path: lua/build/liblua.a 