name: Build iOS Static Library

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
    
    - name: Select Xcode
      run: |
        sudo xcode-select -switch /Applications/Xcode.app
        xcodebuild -version
      
    - name: Prepare build environment
      run: |
        pwd
        ls -la
        echo "Creating build directory..."
        mkdir -p build
        cd build
        echo "Current directory: $(pwd)"
        
        echo "Linking source files..."
        for file in ../*.h ../*.c; do
          if [ -f "$file" ]; then
            echo "Linking: $file"
            ln -sf "$file" .
          fi
        done
        
        echo "Build directory contents:"
        ls -la
        
    - name: Create Xcode project
      run: |
        cd build
        echo "Current directory: $(pwd)"
        chmod +x ../generate-xcodeproj.sh
        ../generate-xcodeproj.sh
        
        echo "Xcode project contents:"
        ls -la lua.xcodeproj/
        
    - name: Build static library
      run: |
        cd build
        echo "Current directory: $(pwd)"
        set -e
        
        echo "Building for iOS devices (arm64)..."
        xcodebuild clean build \
          -project lua.xcodeproj \
          -target lua \
          -configuration Release \
          -sdk iphoneos \
          ONLY_ACTIVE_ARCH=NO \
          BUILD_DIR="$(pwd)/build" \
          CONFIGURATION_BUILD_DIR="$(pwd)/build/Release-iphoneos" \
          ARCHS="arm64" \
          -verbose
        
        echo "Building for iOS Simulator (x86_64, arm64)..."
        xcodebuild clean build \
          -project lua.xcodeproj \
          -target lua \
          -configuration Release \
          -sdk iphonesimulator \
          ONLY_ACTIVE_ARCH=NO \
          BUILD_DIR="$(pwd)/build" \
          CONFIGURATION_BUILD_DIR="$(pwd)/build/Release-iphonesimulator" \
          ARCHS="x86_64 arm64" \
          -verbose
        
        echo "Checking build outputs..."
        ls -la build/Release-iphoneos/
        ls -la build/Release-iphonesimulator/
        
        echo "Creating universal binary..."
        lipo -create \
          build/Release-iphoneos/liblua.a \
          build/Release-iphonesimulator/liblua.a \
          -output liblua.a
        
        echo "Build completed successfully!"
        ls -la liblua.a
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ios-static-library
        path: build/liblua.a
        if-no-files-found: error 