name: iOS Static Library Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build iOS Static Library
    runs-on: macos-13
    
    steps:
    - uses: actions/checkout@v4
      
    - name: Select Xcode
      run: |
        sudo xcode-select -switch /Applications/Xcode.app
        xcodebuild -version
      
    - name: Prepare Build Environment
      run: |
        set -e
        mkdir -p build/lua
        cd build/lua
        echo "Current directory: $(pwd)"
        echo "Listing repository root:"
        ls -la ../..
        echo "Creating symbolic links for source files..."
        for file in ../../*.{c,h}; do
          if [ -f "$file" ]; then
            echo "Linking $file"
            ln -sf "$file" .
          fi
        done
        echo "Listing build directory contents:"
        ls -la
        
    - name: Create Xcode Project
      working-directory: build/lua
      run: |
        set -e
        echo "Generating Xcode project..."
        chmod +x ../../.github/workflows/generate-xcodeproj.sh
        ../../.github/workflows/generate-xcodeproj.sh
        echo "Listing project directory contents:"
        ls -la lua.xcodeproj/
        cat lua.xcodeproj/project.pbxproj
        
    - name: Build Static Library
      working-directory: build/lua
      run: |
        set -e
        
        echo "Building for iOS devices (arm64)..."
        mkdir -p "../Release-iphoneos"
        xcodebuild clean build \
          -project lua.xcodeproj \
          -configuration Release \
          -sdk iphoneos \
          ONLY_ACTIVE_ARCH=NO \
          BUILD_DIR="../" \
          BUILD_FOR_DISTRIBUTION=YES \
          ARCHS="arm64" \
          SKIP_INSTALL=NO \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGN_IDENTITY="" \
          CONFIGURATION_BUILD_DIR="../Release-iphoneos" || exit 1
          
        echo "Building for iOS Simulator (x86_64, arm64)..."
        mkdir -p "../Release-iphonesimulator"
        xcodebuild clean build \
          -project lua.xcodeproj \
          -configuration Release \
          -sdk iphonesimulator \
          ONLY_ACTIVE_ARCH=NO \
          BUILD_DIR="../" \
          BUILD_FOR_DISTRIBUTION=YES \
          ARCHS="x86_64 arm64" \
          SKIP_INSTALL=NO \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGN_IDENTITY="" \
          CONFIGURATION_BUILD_DIR="../Release-iphonesimulator" || exit 1
          
        echo "Creating universal binary..."
        echo "Checking iOS device build output:"
        ls -la "../Release-iphoneos/"
        if [ ! -f "../Release-iphoneos/liblua.a" ]; then
          echo "Error: iOS device library not found"
          exit 1
        fi
        
        echo "Checking iOS simulator build output:"
        ls -la "../Release-iphonesimulator/"
        if [ ! -f "../Release-iphonesimulator/liblua.a" ]; then
          echo "Error: iOS simulator library not found"
          exit 1
        fi
        
        echo "Creating universal binary with lipo..."
        lipo -create \
          "../Release-iphoneos/liblua.a" \
          "../Release-iphonesimulator/liblua.a" \
          -output "../liblua.a"
          
        if [ ! -f "../liblua.a" ]; then
          echo "Error: Failed to create universal binary"
          exit 1
        fi
        
        echo "Checking final universal binary:"
        ls -la "../liblua.a"
        file "../liblua.a"
        lipo -info "../liblua.a"
        
        echo "Build completed successfully"
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ios-static-library
        path: build/liblua.a
        if-no-files-found: error 